# Generated by Django 4.2.9 on 2024-01-21 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=250)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
            ],
        ),
    ]
