# Generated by Django 4.2.9 on 2024-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
