# Generated by Django 4.2.9 on 2024-02-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_prices_distance_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='distance_additional_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prices',
            name='waiting_price',
            field=models.FloatField(),
        ),
    ]
