# Generated by Django 4.2.9 on 2024-02-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_connections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattable',
            old_name='conentent',
            new_name='content',
        ),
    ]
