# Generated by Django 4.2.9 on 2024-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_prices_distance_additional_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='multiple_factor_time',
            field=models.TextField(default='1x'),
            preserve_default=False,
        ),
    ]
